### ISSUE TITLE
Deleting entities after API test

### ISSUE THREAD

**Issue by pesseyjulien** [Codeception/module-doctrine2#27]
Hi,

I'm trying to delete entities created while testing my API, but it does not work.

```
 protected function _after(ApiTester $I)
    {
        $dm = $I->grabService('doctrine.orm.entity_manager');
        $dm->remove($this->worker);
        $dm->remove($this->pro);
        $dm->remove($this->company);
        $dm->flush();
    }
```

I'm getting the entities like this :

`$this->pro = $I->grabEntityFromRepository('AppBundle:User',  array('email' => $proEmail));`

Weird thing, is that if I do something like this :

```
        $this->pro = $I->grabEntityFromRepository('AppBundle:User',  array('email' => $proEmail));


        $this->dm = $I->grabService('doctrine.orm.entity_manager');
        $this->dm->remove($this->pro);
        $this->dm->flush();

        $this->pro = $I->grabEntityFromRepository('AppBundle:User',  array('email' => $proEmail));
```

The second grabEntityFromRepository throw an error : 

> [Doctrine\ORM\NoResultException] No result was found for query although at least one row was expected

But the user is still well in the database.

My config file :

```
actor: ApiTester
modules:
    enabled:
        - Symfony:
            app_path: 'app'
            environment: 'dev'
            part: SERVICES
            em_service : 'doctrine.orm.entity_manager'
        - REST:
            url: 'https://dev.myworks.fr'
            depends: PhpBrowser
        - Doctrine2:
            depends: Symfony
            cleanup: true
```

Any idea what could be happening ?
.
